### ISSUE TITLE
Can i replace item?

### ISSUE THREAD

**Issue by xiaoyao9184** [BlackDice/lill#28]
I want replace head and tail, if i remove head, how can i add new item to head previous?
is that support before or after insertion?

**Comment by danielkcz** [comment]
Wow, you are actually using this tiny library? 😮 That's unexpected. Unfortunately, I am not really up to maintaining this lib, it was essentially an experiment.

I am not entirely sure what are you asking for, would you care to show some example of what are you trying to achieve? Either way, you can remove the head as any other item with `remove` method, but it's not possible to add at the beginning (unshift). It should be possible to create `insert` method quite easily. If you are willing to give it a try, don't be shy and submit a PR.

Also note, that linked lists in general are great for a repeated iteration. Frequent modification turns out a bit more expensive than using a regular array. So if you are hunting for a performance, I would use an array.
